name: CD

on:
  push:
    tags:
      - "*"

jobs:
  build:
    uses: ubio/github-actions/.github/workflows/ci-build.yaml@master
    with:
      name: NodeScript Guides
      image: gcr.io/automation-cloud-registry/nodescript-guides
      ref: ${{ github.ref }}
      file: Dockerfile
    secrets:
      REGISTRY_SECRET: ${{ secrets.GCP_REGISTRY_ACCESS }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

  deploy-production:
    needs: build
    uses: ubio/github-actions/.github/workflows/cd-dispatch-deploy.yaml@master
    with:
      gh_user: NodeScriptLang
      gh_repo: infrastructure
      image_name: nodescript-guides
      env_name: production
      app_path: apps/guides
      auto_merge: true
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
